### ISSUE TITLE
same configuration as yours

### ISSUE THREAD

**Issue by songxing10000** [gabrielcasag/EFI-RYZEN-5600-B550-RX6600#17]
Very good. I am a newbie. Recently I want to buy a machine with the same configuration as yours. Sir, do you have a complete set of configurations, chassis, radiator, power supply, etc.

When purchasing a CPU, a novice like me is still a little afraid of AMD, so I would like to ask, are there any problems with this 5600 in daily work, gaming and entertainment?

**Comment by gabrielcasag** [comment]
Hi @songxing10000!

For hackintoshes, the best combo it is Intel CPU and AMD GPU. You can use Xeons, i3 to i9 and some others.

AMD CPU will work but with limitations, mainly [virtualization](https://dortania.github.io/OpenCore-Install-Guide/macos-limits.html#cpu-support), i.e, no docker, no android studio and thing like that

The mobo chipset it is imporant too, for more hardware infos see the [dortania guide](https://dortania.github.io/OpenCore-Install-Guide/macos-limits.html) and [anti hack buyers guide](https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/)

regards
