### ISSUE TITLE
RTL8111 on MSI B550M-A PRO

### ISSUE THREAD

**Issue by ghost** [gabrielcasag/EFI-RYZEN-5600-B550-RX6600#2]
Hi, i have a problem with my ethernet connection. All goes well after the recovery screen, on this screen i can't download the final SO because it says "internet connection is required" or something like this, same with Safari.

Did you have a problem like this? Do you have any idea with which kext I can solve it?, i think this is weird because i have at least a similar hardware.

Thx for the EFI.

MSI B550M-A PRO
Ryzen 5 5600X
PowerColor RX6600 8GB

**Comment by gabrielcasag** [comment]
Hi @mizziffu

Looking here for your MSI board specs I saw that uses the Realtek RTL8111**H** and that controller is known by have some issues during the installation

My EFI is using the RTL kext on the latest release, I recommend you to give a try to make it work with older releases of the kext: https://github.com/Mieze/RTL8111_driver_for_OS_X/releases


Here are some other links, maybe this help to
https://files.amd-osx.com/RealtekRTL8111.kext_Fixed.zip
https://www.reddit.com/r/hackintosh/comments/e2ywvb/realtek_rtl8111h_not_working_during_installation/
