### ISSUE TITLE
Sleep issue on Gigabyte B550M DS3H

### ISSUE THREAD

**Issue by trwndh** [gabrielcasag/EFI-RYZEN-5600-B550-RX6600#22]
Hi, just wanna ask you is sleep n wake working on your motherboard? mine going to sleep but cannot wake even when i push power button.

**Comment by gabrielcasag** [comment]
Hi @trwndh, yes, i can wake my device, but this subject has many variants.

Try to generate your own SSDT/DSDT patches with https://github.com/corpnewt/SSDTTime

And also take a look at https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html

As I said, it really depends, it could be from a USB dongle you are using or some different component
