### ISSUE TITLE
stuck at amdcpusupport error

### ISSUE THREAD

**Issue by UsetUset2244** [gabrielcasag/EFI-RYZEN-5600-B550-RX6600#7]
stuck at this please help
![IMG_20230430_180041](https://user-images.githubusercontent.com/110706082/235360677-0cec0fe7-b2b0-405d-bafc-4caacd33a497.jpg)

**Comment by gabrielcasag** [comment]
hey man, read the readme carefully, this efi is for my specific PC hardware and is not supposed to work on a notebook.

if your notebook has an amd cpu i suggest u to take a look at https://github.com/NootInc/NootedRed and create your own EFI folder

good luck 🤠

**Comment by UsetUset2244** [comment]
i fixed it by adding the wonogpu in boot args and the amd thing which i forgot what it is name now my notebook boots ventura just fine

**Comment by UsetUset2244** [comment]
btw thanks for closing the issue @gabrielcasag all efies supposed to work you just have to tweak them

**Comment by gabrielcasag** [comment]
awesome @UsetUset2244! 

just saying that all the fixes, patches and tweaks i've made to this EFI are based own my hardware, so maybe some things won't work as well on other hardware, even if I've booted up

**Comment by UsetUset2244** [comment]
thats your opinion snyway thanks for the efi others didnt work

**Comment by UsetUset2244** [comment]
no its not facts its just your opinion ba bye i dont like to continue

**Comment by gabrielcasag** [comment]
great arguments
